# Generated by Django 6.0.1 on 2026-01-28 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=500, verbose_name='Действие')),
                ('action_place', models.CharField(max_length=255, verbose_name='Место выполнения')),
                ('action_time', models.TimeField(verbose_name='Время выполнения')),
                ('frequency', models.PositiveSmallIntegerField(choices=[(1, 'Ежедневно'), (2, 'Каждые 2 дня'), (3, 'Каждые 3 дня'), (4, 'Каждые 4 дня'), (5, 'Каждые 5 дней'), (6, 'Каждые 6 дней'), (7, 'Еженедельно')], default=1, verbose_name='Периодичность (дней)')),
                ('duration', models.PositiveIntegerField(help_text='Не более 120 секунд', verbose_name='Время на выполнение (секунды)')),
                ('reward', models.CharField(blank=True, max_length=255, verbose_name='Вознаграждение')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная привычка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['action_time'],
            },
        ),
    ]
