# Generated by Django 6.0.1 on 2026-01-28 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.PositiveIntegerField(help_text='Не более 120 секунд', validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Время на выполнение (секунды)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ежедневно'), (2, 'Каждые 2 дня'), (3, 'Каждые 3 дня'), (4, 'Каждые 4 дня'), (5, 'Каждые 5 дней'), (6, 'Каждые 6 дней'), (7, 'Еженедельно')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность (дней)'),
        ),
    ]
